site_name: kujira.domains
nav:
- Intro: index.md
- Auctions: auctions.md
- Developers:
  - Architecture: developers/architecture.md
  - Resolving addresses: developers/resolving-addresses.md
theme:
  name: material
  font:
    text: Montserrat
    code: Fira Code
  icon:
    logo: material/rocket-launch
  palette:
  - scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
    primary: red
    accent: blue
  - scheme: default
    toggle:
      icon: material/brightness-7 
      name: Switch to dark mode
    primary: red
    accent: blue
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables
  - toc:
      permalink: true